# Generated by Django 5.0.6 on 2024-05-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='t_users',
        ),
    ]
