# Generated by Django 5.0.6 on 2024-05-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=61),
        ),
    ]
