# Generated by Django 5.0.6 on 2024-05-21 00:20

import apps.chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_room_room_users_room_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=apps.chat.models.get_default_room, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room'),
        ),
    ]
