# Generated by Django 5.0.6 on 2024-06-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_message_room_room_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_users',
        ),
    ]
